name: card_animation_hover
description: "This class is a StatefulWidget that displays a card with a hover animation effect."
version: 0.0.2
homepage: "https://github.com/SwanFlutter/card_animation_hover"

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:


